services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
    - db_data/var/lib/mysql
    environment:
      - MSYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
      - 33060
  app:
    build:
      context:.
      dockerfile:./docker/app/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      -./:/app
    environment:

volumes:
  db_data:
